import type { Metadata } from "next";
import { Geist, Geist_Mono, Changa_One } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const changaOne = Changa_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${changaOne.variable} antialiased min-h-full bg-cover bg-center bg-no-repeat bg-fixed`}
        style={{ backgroundImage: "url('/Images/background2.jpg')" }}
      >
        <main className="`${changaOne.variable}`">
          <div>
            <Navbar />
          </div>
          <div>{children}</div>

          <Footer />
        </main>
      </body>
    </html>
  );
}
